baseurl = "http://blog.brizrobbo.net"
languageCode = "en"
title = "The Blog of Brizrobbo"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/brizrobbo\">Craig Robinson</a> 2017"
disqusShortname = "brizrobbo"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "brizrobbo" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "brizrobbo"
github = "brizrobbo"
email = "brizrobbo@gmail.com"
linkedin = "brizrobbo"
facebook = "brizrobbo"
instagram = ""
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
